/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#1b1b1e',
        primary: '#000000',
        'secondary-fixed': '#e3e1ec',
        'secondary-fixed-dim': '#c6c5cf',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'inverse-primary': '#c8c5ca',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#1a1b22',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#46464e',
        'on-background': '#1c1b1c',
        'inverse-on-surface': '#f4f0ef',
        'surface-container': '#f1eded',
        'secondary-container': '#e3e1ec',
        'amber-warmth': '#F59E0B',
        surface: '#fdf8f8',
        'surface-bright': '#fdf8f8',
        'primary-fixed': '#e4e1e6',
        'electric-blue': '#3B82F6',
        'on-surface-variant': '#47464b',
        'tertiary-fixed': '#e8e2d9',
        'emerald-signal': '#10B981',
        'surface-container-high': '#ebe7e7',
        'on-surface': '#1c1b1c',
        'surface-container-highest': '#e5e2e1',
        'on-secondary': '#ffffff',
        'muted-slate': '#94A3B8',
        'whisper-border': 'rgba(226,232,240,0.5)',
        'outline-variant': '#c8c5cb',
        secondary: '#5d5e66',
        'surface-variant': '#e5e2e1',
        outline: '#77767b',
        'surface-container-lowest': '#ffffff',
        background: '#fdf8f8',
        'surface-dim': '#ddd9d9',
        'tertiary-container': '#1d1b16',
        error: '#ba1a1a',
        'on-secondary-container': '#63646c',
        'on-tertiary-container': '#88837c',
        'on-tertiary-fixed': '#1d1b16',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#c8c5ca',
        'deep-rose': '#E11D48',
        'on-primary-fixed-variant': '#47464a',
        'on-tertiary-fixed-variant': '#494640',
        'tertiary-fixed-dim': '#cbc6bd',
        'surface-container-low': '#f7f3f2',
        'on-primary-container': '#858387',
        'surface-tint': '#5f5e61',
        'primary-container': '#1b1b1e',
        'canvas-white': '#F9FAFB',
        tertiary: '#000000',
        'inverse-surface': '#313030',
        'pure-surface': '#FFFFFF',
      },
      fontFamily: {
        'display-hero': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'metadata-mono': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['clamp(2.25rem, 5vw, 3.75rem)', { lineHeight: '1.1', letterSpacing: '-0.025em', fontWeight: '800' }],
        'body-md': ['1rem', { lineHeight: '1.65', fontWeight: '400' }],
        'metadata-mono': ['0.8125rem', { lineHeight: '1.4', fontWeight: '400' }],
        'headline-lg': ['2rem', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      spacing: {
        'gutter-desktop': '4rem',
        'container-max': '1400px',
        'section-gap-max': '6rem',
        'gutter-mobile': '1rem',
        'gutter-tablet': '2rem',
        'section-gap-min': '3rem',
      },
      boxShadow: {
        diffused: '0 20px 40px -15px rgba(0,0,0,0.05)',
      },
    },
  },
  plugins: [],
};
