// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Slice.Infrastructure.Persistence;

#nullable disable

namespace Slice.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SliceDbContext))]
    partial class SliceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Slice.Infrastructure.Persistence.DailyAgentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ACW")
                        .HasColumnType("REAL");

                    b.Property<double>("AHT")
                        .HasColumnType("REAL");

                    b.Property<double>("ASA")
                        .HasColumnType("REAL");

                    b.Property<string>("AgentEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<double>("AvgHoldTime")
                        .HasColumnType("REAL");

                    b.Property<int>("HC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfHolds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PctContactsOnHold")
                        .HasColumnType("REAL");

                    b.Property<double>("PctSLUnder15Sec")
                        .HasColumnType("REAL");

                    b.Property<double>("PctTransfers")
                        .HasColumnType("REAL");

                    b.Property<string>("Pod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupervisorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "Pod");

                    b.ToTable("DailyAgentRows", (string)null);
                });

            modelBuilder.Entity("Slice.Infrastructure.Persistence.DailyGlobalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConvPct")
                        .HasColumnType("REAL");

                    b.Property<int>("Handled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissedCalls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PctHandled")
                        .HasColumnType("REAL");

                    b.Property<double>("PctMissed")
                        .HasColumnType("REAL");

                    b.Property<double>("PctOrdersWithErrors")
                        .HasColumnType("REAL");

                    b.Property<double>("PctQueued")
                        .HasColumnType("REAL");

                    b.Property<double>("PctTransferred")
                        .HasColumnType("REAL");

                    b.Property<string>("Pod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Queued")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefundedOrders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferredCalls")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "Pod");

                    b.ToTable("DailyGlobalRows", (string)null);
                });

            modelBuilder.Entity("Slice.Infrastructure.Persistence.ProcessingJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByEmail");

                    b.ToTable("ProcessingJobs", (string)null);
                });

            modelBuilder.Entity("Slice.Infrastructure.Persistence.ShopCallMetricsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HandledCalls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissedCalls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverflowCalls")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PctHandled")
                        .HasColumnType("REAL");

                    b.Property<double>("PctMissedOfQueued")
                        .HasColumnType("REAL");

                    b.Property<double>("PctOverflow")
                        .HasColumnType("REAL");

                    b.Property<double>("PctQueued")
                        .HasColumnType("REAL");

                    b.Property<double>("PctTransferred")
                        .HasColumnType("REAL");

                    b.Property<string>("PodId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("QueueCalls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCalls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransferredCalls")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WeekStart");

                    b.HasIndex("ReportId", "ShopId", "PodId", "WeekStart");

                    b.ToTable("ShopCallMetricsRows", (string)null);
                });

            modelBuilder.Entity("Slice.Infrastructure.Persistence.ShopDailyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConversionRate")
                        .HasColumnType("REAL");

                    b.Property<double>("ErrorRate")
                        .HasColumnType("REAL");

                    b.Property<int>("RefundedOrders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalOrders")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportId", "ShopId");

                    b.ToTable("ShopDailyRows", (string)null);
                });

            modelBuilder.Entity("Slice.Infrastructure.Persistence.SliceReportEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedByEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MergedCsvPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("MergedXlsxPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("GeneratedByEmail");

                    b.HasIndex("ReportDate");

                    b.ToTable("SliceReports", (string)null);
                });

            modelBuilder.Entity("Slice.Infrastructure.Persistence.DailyAgentEntity", b =>
                {
                    b.HasOne("Slice.Infrastructure.Persistence.SliceReportEntity", "Report")
                        .WithMany("DailyAgents")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Slice.Infrastructure.Persistence.DailyGlobalEntity", b =>
                {
                    b.HasOne("Slice.Infrastructure.Persistence.SliceReportEntity", "Report")
                        .WithMany("DailyGlobal")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Slice.Infrastructure.Persistence.ShopCallMetricsEntity", b =>
                {
                    b.HasOne("Slice.Infrastructure.Persistence.SliceReportEntity", "Report")
                        .WithMany("ShopCallMetrics")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Slice.Infrastructure.Persistence.ShopDailyEntity", b =>
                {
                    b.HasOne("Slice.Infrastructure.Persistence.SliceReportEntity", "Report")
                        .WithMany("ShopDaily")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Slice.Infrastructure.Persistence.SliceReportEntity", b =>
                {
                    b.Navigation("DailyAgents");

                    b.Navigation("DailyGlobal");

                    b.Navigation("ShopCallMetrics");

                    b.Navigation("ShopDaily");
                });
#pragma warning restore 612, 618
        }
    }
}
